trigger:
- master

# strategy:
#   matrix:
#     linux:
#       operatingSystem: 'ubuntu-latest'
#     mac:
#       operatingSystem: 'macos-latest'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - bash: echo "Running build job"

- stage: DevDeploy
  jobs:
  - deployment: DevDeployJob
    environment: Dev
    strategy:
     runOnce:
       deploy:
         steps:
           - script: Deploy to Dev

- stage: QADeploy
  jobs:
  - deployment: QADeployJob
    environment: Dev
    strategy:
     runOnce:
       deploy:
         steps:
           - script: Deploy to QA

